### ISSUE TITLE
how to use map_fsaverage_to_hcp.sh

### ISSUE THREAD

**Issue by ReedOnePeck** [zijin-gu/meshconv-decoding#2]
This is a very good work and I am interested in the model you proposed. However, when reconstructing an image, the NSD data used have to be projected in a mesh, what should the input of tmap_fsaverage_to_hcp.sh look like? How to convert data formats？Thank you very much for your reply

**Comment by zijin-gu** [comment]
Hi,

As the script name suggests, the input to it should be the voxel-level brain response in fsaverage space. The script is provided as a helper to map voxel data to surface data.
