### ISSUE TITLE
Code for SSIM Metric

### ISSUE THREAD

**Issue by ozcelikfu** [zijin-gu/meshconv-decoding#3]
I couldn't replicate the results for the SSIM metric. Could you tell me which SSIM code you used? Thank you

**Comment by zijin-gu** [comment]
The function I used is the structural_similarity from  skimage.metrics. We first convert the image to grey scale using rgb2grey and then use code:
`structural_similarity(gt, recon, multichannel=True, gaussian_weights=True, sigma=1.5, use_sample_covariance=False, data_range=1.0)`

**Comment by zijin-gu** [comment]
``
