### ISSUE TITLE
Can you describe more about the data you have used?

### ISSUE THREAD

**Issue by freya107** [zijin-gu/meshconv-decoding#4]
Thank you for providing your code republicly.But I am a little confused about what kind of data you have used, because the NSD dataset is too big. Can you discribe more about which data you have used, and how to get it and preprocess it? Thank you very much.

**Comment by zijin-gu** [comment]
Thanks for the question.
The data I used is the betas_fithrf_GLMdenoise_RR version in NSD. You can access to NSD as it is a publicly available dataset.
