### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by HuangWanqiu** [zijin-gu/meshconv-decoding#5]
Can you please provide the data used in 'utils4image/dataloaders.py' for the variables 'image_feats' (line 17), 'response_data' (lines 19 and 21), 'image_data_set' (line 53), 'image_feats' (line 56), and 'response_data' (lines 58 and 60)?
![image](https://github.com/zijin-gu/meshconv-decoding/assets/12394382/ef200c76-6a87-4971-a613-719e7b13fedd)

**Comment by zijin-gu** [comment]
Hi, NSD is already publicly available at https://naturalscenesdataset.org/.

**Comment by HuangWanqiu** [comment]
> Hi, NSD is already publicly available at https://naturalscenesdataset.org/.

The numpy files used in 'utils4image/dataloaders.py' appear to be preprocessed, which is inconsistent with the data available on the NSD website.
Is it possible to provide the preprocessed files used in 'meshconv-decoding' project so that we can directly run the project?
Thanks!

**Comment by zijin-gu** [comment]
Some of the data on NSD website are preprocessed and those were what we used in our paper. What we did was only prepare them in certain format that is easy for the model to read. I am not allowed to provide the data we used directly since the original data is available publicly. I suggest you to follow the instructions on how to prepare the data.

**Comment by HuangWanqiu** [comment]
> Some of the data on NSD website are preprocessed and those were what we used in our paper. What we did was only prepare them in certain format that is easy for the model to read. I am not allowed to provide the data we used directly since the original data is available publicly. I suggest you to follow the instructions on how to prepare the data.

Ok, I'll try. Thanks for your reply.

**Comment by happylufei** [comment]
> Some of the data on NSD website are preprocessed and those were what we used in our paper. What we did was only prepare them in certain format that is easy for the model to read. I am not allowed to provide the data we used directly since the original data is available publicly. I suggest you to follow the instructions on how to prepare the data.

hello, could you provide the location of these instructions?

**Comment by happylufei** [comment]
> Some of the data on NSD website are preprocessed and those were what we used in our paper. What we did was only prepare them in certain format that is easy for the model to read. I am not allowed to provide the data we used directly since the original data is available publicly. I suggest you to follow the instructions on how to prepare the data.

hello,could you provide the location of these instructions?
