### ISSUE TITLE
About the preprocessing of fMRI data.

### ISSUE THREAD

**Issue by happylufei** [zijin-gu/meshconv-decoding#6]
Hello, thank you very much for your work. Could you please explain in more detail how S1_surface32k_mean.npy is generated from data such as lh_betas_session01.func.gii and rh_betas_session01.func.gii? I'm having difficulty figuring out how this data is organized, and I was wondering if you could provide the code for this processing. Thank you very much.

**Comment by zijin-gu** [comment]
Hi, I have shared the preprocessed data. Please check the readme.
